In [ ]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    "Name": ["Amit", "Neha"],
    "Age": [23, 25]
})
df

   Name  Age
0  Amit   23
1  Neha   25

In [5]:
df["Name"].isin(["Amit"])

0     True
1    False
Name: Name, dtype: bool

In [12]:
df["Age"].between(20, 24)

0     True
1    False
Name: Age, dtype: bool

In [13]:
df.query("Age > 24")

   Name  Age
1  Neha   25

In [20]:
# .value_counts()
df = pd.DataFrame({
    "City": ["Delhi", "Mumbai", "Delhi", "Lucknow", "Mumbai"]
})

df["City"].value_counts()

City
Delhi      2
Mumbai     2
Lucknow    1
Name: count, dtype: int64

In [17]:
# Using .apply() function -> Can be applied in both Seires and DataFrame
# Meaning - Apply function on rows or columns.
df2 = pd.DataFrame({
    "Salary": [10000, 20000, 30000]
})

df2["Bonus"] = df2["Salary"].apply(lambda x : x*1.5)

df2["Total"] = df2["Salary"] + df2["Bonus"]
df2

   Salary    Bonus    Total
0   10000  15000.0  25000.0
1   20000  30000.0  50000.0
2   30000  45000.0  75000.0

In [19]:
# Using .map() function => Can only be applied on Series data
# Meaning - Element-wise transformation (only for Series)
df3 = pd.DataFrame({
    "Marks": [50, 70, 90 , 20 , 56 , 67 , 48 , 71 , 66 , 78 , 92 , 83]
})

df3["Grade"] = df3["Marks"].map(lambda x : "Pass" if x >= 60 else "Fail" )
df3

    Marks Grade
0      50  Fail
1      70  Pass
2      90  Pass
3      20  Fail
4      56  Fail
5      67  Pass
6      48  Fail
7      71  Pass
8      66  Pass
9      78  Pass
10     92  Pass
11     83  Pass

In [31]:
# Using .pivot() function
# Meaning - pivot() is used to restructure data (change its shape)
# no duplicate handling and aggregation function support like pivot_table

df4 = pd.DataFrame({
    "Date": ["Jan", "Jan", "Feb", "Feb"],
    "Product": ["A", "B", "A", "B"],
    "Sales": [100, 200, 150, 250]
})
df4

  Date Product  Sales
0  Jan       A    100
1  Jan       B    200
2  Feb       A    150
3  Feb       B    250

In [35]:
df4.pivot( index = "Date" , columns="Product" , values= "Sales")

# Limitation (IMPORTANT) - > Pivot fails if duplicate values exist

Product    A    B
Date
Feb      150  250
Jan      100  200

In [36]:
# Solution - pivot_table()
pd.pivot_table(df4, index="Date", columns="Product", values="Sales", aggfunc="mean")

Product      A      B
Date
Feb      150.0  250.0
Jan      100.0  200.0

In [37]:
# pivot_table Example  - 1
# Handles duplicate data by giving there mean
# Aggregation functions can be applied on it


df = pd.DataFrame({
    "Month": ["Jan", "Jan", "Feb", "Feb"],
    "Product": ["A", "B", "A", "B"],
    "Sales": [100, 200, 150, 250]
})

pd.pivot_table(df, index="Month", columns="Product", values="Sales")

Product      A      B
Month
Feb      150.0  250.0
Jan      100.0  200.0

In [38]:
# pivot_table Example  - 2
df = pd.DataFrame({
    "Month": ["Jan", "Jan", "Feb", "Feb"],
    "City": ["Delhi", "Mumbai", "Delhi", "Mumbai"],
    "Sales": [100, 200, 150, 250]
})

pd.pivot_table(df, index=["Month", "City"], values="Sales")

              Sales
Month City
Feb   Delhi   150.0
      Mumbai  250.0
Jan   Delhi   100.0
      Mumbai  200.0

In [39]:
# pivot_table Example - 3
pd.pivot_table(df, index="Month", columns="City", values="Sales", aggfunc="sum", margins=True)

City   Delhi  Mumbai  All
Month
Feb      150     250  400
Jan      100     200  300
All      250     450  700

In [28]:
# Date-Time Functions
df = pd.DataFrame({
    "date": ["2024-01-01", "2024-02-15"]
})

df["date"] = pd.to_datetime(df["date"])

df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day"] = df["date"].dt.day

df

        date  year  month  day
0 2024-01-01  2024      1    1
1 2024-02-15  2024      2   15